### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by dandv** [qklabs/qksms#164]
Just found this app on F-Droid. The description was promising: the stock SMS app with extra features. I've been looking for per-contact notification settings - at least different ringtones.

Is there a feature list detailing how this fork is different from stock?

**Comment by moezbhatti** [comment]
Not really, as it's not a fork. It was written from the ground up as an independant app

**Comment by mvdan** [comment]
To build on this - I am lazy when writing descriptions. If either of you has a better description, feel free to post a merge request on fdroiddata.

**Comment by dandv** [comment]
Maybe it's just me, but when picking among multiple apps that do the same thing (Handcent, ChompSMS, stock etc.), how am I supposed to decide which to install without something like a feature list?

**Comment by mvdan** [comment]
Understandable, patches welcome :) I don't use all the apps that I add and update in F-Droid. I don't keep track of the number I added and wrote descriptions for, but it's probably in the hundreds.

Since our metadata is in a git repo, it should be easy for people to contribute better descriptions if they know apps well.
