### ISSUE TITLE
Using 40 permissions. For an SMS app?

### ISSUE THREAD

**Issue by iamcrocbait** [qklabs/qksms#234]
I was interested in this application until I saw what permissions are required to run this software. 40 permissions seems rather excessive for an application that essentially reads/writes SMS. There's no detailed info on the additional features this application brings to the party.

For instance, why would it need to "Control Near Field Communication", "Change Wi-Fi state", "Fine (GPS) location", "Take pictures and videos", "Record audio", "Directly call phone numbers"?

Perhaps it would be helpful if more information could be provided about this application. That way people like me could understand the reasons behind such permission requests.

**Comment by licaon-kter** [comment]
How do you think you can attach GPS location? Record video/sound clip to attach via MMS? Have a call icon that calls the person you messaged? And so and so?

**Comment by l3d00m** [comment]
Some of the good points of open source apps is that you can see that apps aren't doing malicious things with the permissions.

**Comment by iamcrocbait** [comment]
@licaon-kter thanks for that. That is the type of info I'm after. It's pretty hard to find a list of features anywhere (and how permissions tie into those features).

@l3d00m Very true. And that's why I generally prefer open source apps over others. I'm fairly new to Android and it generally amazes me how many permissions apps require in order to function.

**Comment by moezbhatti** [comment]
Nearly all of them are being used. A couple of them are there for future features, and they were added early on so that people can still get automatic updates when the feature is implemented (rather than having to accept a new permission)

Luckily, the app is open source, so you know there's nothing to hide :)

**Comment by jonblack** [comment]
I think this is a good and valid question. I haven't installed the app yet because it does seem suspicious at first glance. A list of permissions and the reasons they're needed would help.

**Comment by licaon-kter** [comment]
@jonblack: While reading hte previous posts, what permission seems out of place?

**Comment by jonblack** [comment]
@licaon-kter It's just surprising. I think of an SMS app as being able to read/write/send/receive SMS messages and view contacts. I understand that qksms offers additional features, as mentioned above, that require extra permissions, but given that I don't expect that, it's easy to become paranoid. Also, given the whole heartbleed saga, open source guarantees nothing. The only permissions on the list that I don't understand being there are the network connection ones. Is that because MMS messages go over WiFi rather than the carrier?

**Comment by licaon-kter** [comment]
I think MMS need to go over carrier no matter what.

**Comment by moezbhatti** [comment]
There are a couple carriers where MMS can go over WiFi

The network permissions are also needed for the donations in the app
