### ISSUE TITLE
[FEATURE REQUEST] Fetch images (from URL) Option 

### ISSUE THREAD

**Issue by pikurasa** [qklabs/qksms#365]
Hi,

I am on a team that uses GroupMe. They just have to have it. However, I refuse to install the proprietary app on my phone (I don't even have Google Play on my phone).

GroupMe apparently allows members to opt non-members in by setting up an account for them with their phone number. When this happens, the person without the software (me) receives a text message instead (maybe it is called MMS--unsure). However, it does not fetch the images.

Is it possible to:
1. Create a "fetch URL images" option for a thread?
This would, when switched on, a) fetch all URL images from the server automatically for a certain thread and b) keep it locally on the phone so that it could c) display the image in the thread.
2. Make that option available to be torified?

Many thanks!
Thanks!
Devin

**Comment by dethstar** [comment]
That would be https://github.com/qklabs/qksms/commit/7ae7e13b26660e8d63bc046bb4fcca101e3805b9

**Comment by pikurasa** [comment]
@dethstar Thanks. I am on 2.5.1 (from F-Droid) and I couldn't find the option (still can't find it). I will do more homework... Thanks, again!

**Comment by pikurasa** [comment]
Oh, I see (I just cloned it). It was put in January 8th. Can't wait to try it out! You are totally getting a donation from me for making this happen!

This way I can suggest an alternative to GroupMe. Thnx!

**Comment by moezbhatti** [comment]
No problem! I'll release the update in the next few days

**Comment by homersimpsons** [comment]
Hi, Thank you for this function :) I don't even know it exist before I see it in issue.
Then i would have a try, I go on google to fnd a small picture (http://www.maison-image.fr/images/admin.png)
I sent it to me ... and see nothing. Bit I know WHY:
This is a PNG with alpha and the icon is dark, But i choose a dark background for QK then I can't view this images because Dark over Dark make no image.

How to solve this ??
Set a white background (4px higher than the image) with 2px for each border of the image, that will help to highlight the pictures from de background. But it can be easier to just set a background of the same size than the image.
