### ISSUE TITLE
Message list showing contact number rather than the contact name

### ISSUE THREAD

**Issue by isaactsg** [qklabs/qksms#9]
In the message drawer with the list of conversations some of my contacts show their correct names, but some just show the phone number, even though they have a name in my contacts.

**Comment by srcreigh** [comment]
@isaactsg can you give examples of the phone numbers that don't work? We'll need to know the number you have saved in the contact entry, and the number that is on the SMS message (i.e. that you see in the conversation list). Example below. Feel free to censor the last 4 digits for privacy reasons.

**Country**: France
**Contact number**: 06 12 34 56 78
**SMS number**: +33612345678

**Comment by srcreigh** [comment]
I am marking this as a bug because we already have a case of this received via email for numbers in France.

**Comment by Ravenstencil** [comment]
US
All of my contacts have full ten digit numbers (required by my AT&T carrier)
719-459-####

**Comment by toxicbubble** [comment]
Just some additional details that I've noticed as I've also seen this issue in New Zealand with our +64 international code. 

This is seems to affect contacts if the number stored in the contact differs from that in the 'details' of the first message in that conversation thread. For example, if the first in a thread sms is from 021 234 5678 and the contact is saved as +64212345678 then it won't display the contact correctly. Same if the receiving number and contact number are swapped the other way.  (note: the leading zero is dropped when using the full international - not sure if that's a local thing or the same elsewhere). 

I'm not sure why the number that shows up in the sms database sometimes has the full country code and sometimes does not. Maybe carrier related? Various sms through the history of a conversation thread seem to flip backwards and forwards between being received from the international vs non-international prefixed format.

**Comment by moezbhatti** [comment]
Fixed a few weeks ago

**Comment by bene86** [comment]
I just downloaded QKSMS from Google Play and overall, I like it a lot. But for me there are still some conversations where the number is not replaced by the contact name. My contacts in my address book are stored exclusively with the area code and it is exactly as toxicbubble commented. The first message in a corrupted conversation is always stored with the number without the area code. If I delete the area code from the corresponding contact and restart QKSMS everything is fine (but of course I don't want the contact without area code).

**Comment by rphair** [comment]
I had this problem with many of my contacts showing up as numbers rather than names in QKSMS from the beginning: it's a great app otherwise.  Following a suggestion above (@toxicbubble comment on 1 Jul 2015) I used "SMS Backup & Restore" to backup, search & replace any leading 0 in the phone number with the country code (in my case, +353 = Ireland) and load from backups again.

It worked perfectly, with those number-only contacts showing up for the first time as names.   Very disappointingly, new contacts I have SMS'd through the dialer are still contracted to numbers with a leading 0 in the outgoing message, which are stored that way going forward.  QKSMS can't match these unprefixed numbers with the proper contact phone numbers having a the full country code, so they're displayed as number-only.  You can see the preceding 0 for _all_ the un-named contacts in the XML dump of the SMS database from "SMS Backup & Restore."

I can't keep doing this manual clean-up operation again and again to keep rationalising my Conversation list, so need to know what was done to "fix" this problem, what settings I might use on the Google Play market version to make this "fix" apparent, how to get whatever version of the QKSMS software that contains the "fix" as reported by the developer on 24 Aug 2015.

I also think it would make great sense to re-open this bug report, or link it to wherever common reports of this problem are being investigated if it's a duplicate.  BTW I'm on version 2.7.3 of QKSMS with Android 6.x on a Nexus 5.

**Comment by catscarlet** [comment]
Just downloaded QKSMS, and got the same problem.

**Comment by rphair** [comment]
I have had to abandon QKSMS in favour of a closed-source commercial app in the last couple of months for this reason.  Even if I could automate a daily procedure to dump the backups, search & replace any local phone numbers to country coded numbers, and then restore from the corrected backup, it still wouldn't fix the problem on the day that new contact was calling... the most important period of all.

Until the author is willing to correlate this issue with something that truly has been "fixed," I will have to consider it just another open source project with a lot of potential but without real support.

**Comment by moezbhatti** [comment]
Thanks for the feedback everyone. I plan to address this in the new update, which I started working on last week. It's a major overhaul of the app, so it'll take a little bit of time before it's ready to launch, but I'm planning to release the beta version within the next month

**Comment by lepidas** [comment]
I have the same problem, for example
in my contacts I have Rade +47 409 04 002
When Rade sends me message the sender is not Rade but 40904002

**Comment by ryandward** [comment]
Still have the problem
